added firebase auth and made prisma client globally usable
donategifts/donategifts-backend pull request #11
Opened 2021-08-04 20:38 UTC by gnorbsl

2021-08-04 21:03 UTC, Enubia requested changes
please also run the tests locally and fix the occurring errors

2021-08-04 21:03 UTC, Enubia commented on src/helper/authMiddleware.ts
> +  const user = await prisma.user.findUnique({
try-catch this please in case the DB is not reachable

2021-08-04 21:03 UTC, Enubia commented on src/helper/authMiddleware.ts
> +    throw new Error('CREATE NEW USER OR SOMETHING');
use our custom error class for this ;)

2021-08-04 21:03 UTC, Enubia commented on src/helper/authMiddleware.ts
> +    console.log(error);
logger.error instead of console

2021-08-05 07:51 UTC, Enubia requested changes

2021-08-05 09:28 UTC, gnorbsl commented on src/helper/authMiddleware.ts
> +  const user = await prisma.user.findUnique({
there is already a try catch in the calling function

2021-08-05 09:29 UTC, gnorbsl commented on src/db/prisma.ts
> +  global.prisma = prisma;
how can I use apollo context in the auth middleware?

2021-08-05 10:35 UTC, gnorbsl commented on package.json
> +    "dev": "GOOGLE_APPLICATION_CREDENTIALS=donate-gifts.json nodemon --inspect=0.0.0.0:9229 -e ts,js -w src --exec node -r ./loadEnv.js -r ts-node/register src/",
I tried, it'll be overwritten by my local work setup for whatever reason

2021-08-05 10:39 UTC, Enubia commented on package.json
> +    "dev": "GOOGLE_APPLICATION_CREDENTIALS=donate-gifts.json nodemon --inspect=0.0.0.0:9229 -e ts,js -w src --exec node -r ./loadEnv.js -r ts-node/register src/",
hmm ok, well then leave it for now, but also add it to the default.env file please

2021-08-05 10:55 UTC, Enubia submitted a review, later dismissed

2021-08-06 19:14 UTC, Enubia submitted a review, later dismissed

2021-08-11 05:06 UTC, Enubia commented on .github/workflows/build.yml
> +on: [push, pull_request]
I removed the pull_request on purpose, if you do that it runs twice in opened PRs

2021-08-11 13:54 UTC, Jacobjeevan commented on prisma/schema.prisma
> +  @@index([wishcardId], name: "donation_wishcardId_idx")
Wishcard to donation is 1:1, so the index here is unnecessary, no? :thinking:

2021-08-11 13:55 UTC, Jacobjeevan commented on prisma/schema.prisma
> +  wishcard_userTowishcard_createdBy wishcard[]     @relation("userTowishcard_createdBy")
minor thing, but mind renaming/shortening this to wishcard_createdBy? (Same in line 161).

2021-08-11 14:04 UTC, Jacobjeevan commented on prisma/schema.prisma
> +  user_userTowishcard_createdBy user            @relation("userTowishcard_createdBy", fields: [createdBy], references: [id])
minor thing, but mind renaming/shortening this to wishcard_createdBy? (Same in line 124).

Edit: Hmm, I suggest removing this field (keep it similar to what we had earlier - wish card being related only to the agency and not directly to the user).

We want to display/make cards editable to users of a particular agency anyways.

2021-08-12 05:20 UTC, Enubia commented on prisma/schema.prisma
> +  user_userTowishcard_createdBy user            @relation("userTowishcard_createdBy", fields: [createdBy], references: [id])
this field is auto-generated by prisma, we don't use that anywhere right now

2021-08-16 06:23 UTC, Enubia commented on prisma/schema.prisma
> +  @@index([wishcardId], name: "donation_wishcardId_idx")
@gnorbsl

2021-08-16 12:06 UTC, merged